cache:
  directories:
    - $HOME/.m2

language: java

jdk:
  - openjdk8

services:
  - redis-server

script:
  - mvn test -B

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
